version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "some-dependency"
        versions:
          - ">=1.0.0 <2.0.0"
    commit-message:
      prefix: "chore"
      include: "scope"
    rebase-strategy: "auto"
