/**
 * Custom release notes transformer for Semantic Release.
 * Transforms generated release notes into a standardized enterprise format.
 *
 * @param {string} releaseNotes - Raw release notes generated by Semantic Release.
 * @returns {string} - Formatted release notes.
 */
module.exports = async function transformReleaseNotes(releaseNotes) {
  try {
    const currentDate = new Date().toISOString().split('T')[0];
    const formattedNotes = `
    ## 🚀 Release Notes
    Date: ${currentDate}

    ### 📝 Highlights
    ${extractHighlights(releaseNotes)}

    ### 🔧 Changes
    ${releaseNotes}

    ### 📘 Documentation
    For more details, refer to the [documentation](https://docs.yourcompany.com/releases).

    ### 🛠 Support
    For support, contact the [DevOps Team](mailto:devops@yourcompany.com).
    `;
    return formattedNotes;
  } catch (error) {
    console.error('Error transforming release notes:', error);
    throw error;
  }
};

/**
 * Extracts highlights from release notes (e.g., breaking changes, new features).
 *
 * @param {string} releaseNotes - Raw release notes.
 * @returns {string} - Extracted highlights.
 */
function extractHighlights(releaseNotes) {
  const highlights = [];
  const lines = releaseNotes.split('\n');
  for (const line of lines) {
    if (line.startsWith('BREAKING CHANGE') || line.startsWith('feat')) {
      highlights.push(line.trim());
    }
  }
  return highlights.length > 0 ? highlights.join('\n') : 'No major highlights in this release.';
}
