name: Dependency Audit

on:
  schedule:
    - cron: '0 5 * * 0' # Weekly on Sunday at 5 AM UTC
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pnpm install

      - name: Audit Dependencies
        run: pnpm audit --audit-level=high
