name: Lint Code

on:
  push:
    branches:
      - main
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.json'
  pull_request:
    branches:
      - main

jobs:
  # Reuse shared dependency cache job
  cache-dependencies:
    name: Cache Dependencies
    uses: ./.github/workflows/shared-dependency-cache.yml
    with:
      node-version: '20'

  # Main linting job
  lint-code:
    needs: cache-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pnpm install

      - name: Run Linter
        run: pnpm lint
